version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: backend-nodejs
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
    restart: 'always'
